[theme]
# Primary accent for interactive elements
# primaryColor = '#fac88f'

# Background color for sidebar and most interactive widgets
# secondaryBackgroundColor = '#fbf3ea'

# Color used for almost all text
# textColor = '#b7bcc1'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"

font = "sans serif"
